version: 2

models:
  - name: stg_customers
    description: "Staging table for customers"
    columns:
      - name: customer_id
        description: "Unique ID for each customer"
        tests:
          - not_null
          - unique
      - name: full_name
        description: "Customer's full name"
        tests:
          - not_null
      - name: email
        description: "Customer email address"
      - name: join_date
        description: "Date the customer joined"
        tests:
          - not_null

  - name: stg_orders
    description: "Staging table for orders"
    columns:
      - name: order_id
        description: "Unique ID for each order"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "ID of customer who made the order"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: order_date
        description: "Date the order was made"
        tests:
          - not_null
      - name: total_amount
        description: "Total amount for the order"
        tests:
          - not_null

  - name: stg_order_items
    description: "Staging table for individual items in orders"
    columns:
      - name: order_item_id
        description: "Unique ID for each order item"
        tests:
          - not_null
          - unique
      - name: order_id
        description: "Order ID this item belongs to"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        description: "Product ID of the item"
        tests:
          - not_null
      - name: quantity
        description: "Quantity ordered"
        tests:
          - not_null
      - name: line_total
        description: "Line total (quantity x price)"
        tests:
          - not_null

  - name: stg_products
    description: "Staging table for products"
    columns:
      - name: product_id
        description: "Unique ID for each product"
        tests:
          - not_null
          - unique
      - name: product_name
        description: "Name of the product"
        tests:
          - not_null
      - name: category
        description: "Product category"
        tests:
          - not_null
      - name: price
        description: "Price of the product"
        tests:
          - not_null

  - name: stg_loyalty_points
    description: "Staging table for customer loyalty points"
    columns:
      - name: loyalty_id
        description: "Unique ID for each loyalty transaction"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Customer ID for loyalty transaction"
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
      - name: points_earned
        description: "Points earned in this transaction"
        tests:
          - not_null
      - name: transaction_date
        description: "Date of loyalty points transaction"
        tests:
          - not_null
      - name: source
        description: "Source of points (e.g., purchase, promo)"
        tests:
          - not_null
