version: 2

models:
  - name: mart_customer_revenue
    description: "Customer revenue & ranking for analytics"
    columns:
      - name: customer_id
        description: "Unique ID for each customer"
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('int_customer_order_metrics')
              field: customer_id
      - name: full_name
        description: "Customer full name"
      - name: total_revenue
        description: "Total revenue for the customer"
        tests:
          - not_null
          
      - name: order_count
        description: "Total orders placed by the customer"
        tests:
          - not_null
          
      - name: first_order_date
        description: "Date of first order"
      - name: last_order_date
        description: "Date of last order"
      - name: spend_rank
        description: "Dense rank of customer based on total revenue"

  - name: mart_loyalty_tiers
    description: "Customer loyalty tiers based on points"
    columns:
      - name: tier
        description: "Bronze (<100), Silver (100–499), Gold (>=500)"
      - name: tier_count
        description: "Number of customers in this tier"
        tests:
          - not_null
          
      - name: tier_total_points
        description: "Sum of loyalty points for this tier"
        tests:
          - not_null
         

  - name: mart_high_spend_low_loyalty
    description: "Customers with high spend but low loyalty points"
    columns:
      - name: customer_id
        description: "Unique customer ID"
        tests:
          - not_null
          - relationships:
              to: ref('int_customer_order_metrics')
              field: customer_id
      - name: full_name
        description: "Customer full name"
      - name: total_spend
        description: "Total revenue spent by customer"
        tests:
          - not_null
          
      - name: total_points
        description: "Total loyalty points earned"
        tests:
          - not_null
          

  - name: mart_churn_risk
    description: "Customers at risk of churn based on inactivity and loyalty"
    columns:
      - name: customer_id
        description: "Unique customer ID"
        tests:
          - not_null
          - relationships:
              to: ref('int_customer_order_metrics')
              field: customer_id
      - name: full_name
        description: "Customer full name"
      - name: last_order_date
        description: "Last date customer placed an order"
      - name: total_points
        description: "Total loyalty points earned"
        tests:
          - not_null
          
